app:
  name: "go-mvc"
  version: "1.0.0"
  environment: "development"
  debug: true
  timezone: "UTC"
  graceful_stop: "30s"

server:
  http:
    host: "0.0.0.0"
    port: 8080
    read_timeout: "30s"
    write_timeout: "30s"
    idle_timeout: "120s"
    max_header_bytes: 1048576
    tls:
      enabled: false
      cert_file: ""
      key_file: ""
    cors:
      enabled: true
      allowed_origins: ["http://localhost:3000", "http://localhost:3001"]
      allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"]
      allowed_headers: ["*"]
      exposed_headers: ["X-Total-Count"]
      max_age: 86400
  grpc:
    host: "0.0.0.0"
    port: 9090

database:
  primary:
    driver: "postgres"
    host: "localhost"
    port: 5432
    username: "postgres"
    password: "postgres"
    database: "go_mvc_dev"
    ssl_mode: "disable"
    max_open_conns: 25
    max_idle_conns: 25
    conn_max_lifetime: "5m"
    conn_max_idle_time: "5m"
    log_level: "info"
  replica:
    driver: "postgres"
    host: ""
    port: 5432
    username: ""
    password: ""
    database: ""
    ssl_mode: "disable"
    max_open_conns: 10
    max_idle_conns: 10
    conn_max_lifetime: "5m"
    conn_max_idle_time: "5m"
    log_level: "warn"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  dial_timeout: "5s"
  read_timeout: "3s"
  write_timeout: "3s"
  idle_timeout: "5m"

logger:
  level: "debug"
  encoding: "console"
  output_paths: ["stdout"]
  error_paths: ["stderr"]
  development: true

jwt:
  secret: "development-secret-key-change-in-production"
  access_expiry: "15m"
  refresh_expiry: "168h"
  issuer: "go-mvc"
  audience: "go-mvc-users"

metrics:
  enabled: true
  path: "/metrics"
  port: 9090

tracing:
  enabled: true
  service_name: "go-mvc"
  endpoint: "localhost:4318"
  sample_rate: 1.0

rate_limit:
  enabled: true
  rps: 100
  burst: 200

messaging:
  nats:
    url: "nats://localhost:4222"
    max_reconnects: 10
    reconnect_wait: "2s"
    timeout: "5s"
    drain_timeout: "30s"

external:
  payment_service:
    base_url: "https://api.stripe.com"
    api_key: "sk_test_..."
    timeout: "30s"
    max_retries: 3
  email_service:
    provider: "smtp"
    smtp:
      host: "localhost"
      port: 1025
      username: ""
      password: ""
      from: "noreply@go-mvc.dev"
      tls: false
    api_key: ""
    from: "noreply@go-mvc.dev"

feature:
  enable_swagger: true
  enable_pprof: true
  enable_health_check: true
  enable_metrics: true
